### ISSUE TITLE
CSS Animated Clock 

### ISSUE THREAD

**Issue by xyz031** [Am10aN16/hacktoberfest2023#5]
Make a clock animation with moving minute and hour hands.
![cl](https://github.com/Am10aN16/hacktoberfest2023/assets/119855827/d75c717b-5224-44dc-a944-414c62a244a2)

**Comment by xyz031** [comment]
Please assign me this under hacktoberfest2023.

**Comment by arunbossakkk** [comment]
I want to contribute on this please assign

**Comment by itzanway** [comment]
please assign this issue to me under hacktoberfest_2023

**Comment by Aastha7078** [comment]
Hii sir, can u pls assign this to me

**Comment by itzanway** [comment]
Done with it you can now merge it sir request has been sent

**Comment by saurav2208** [comment]
@Am10aN16 Please assign me the issue. I would like to contribute to your work.

**Comment by vs-29** [comment]
I want to contribute over this.
